### ISSUE TITLE
Codecov badge is broken

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/base-repo#114]
**Describe the bug**
The badge for codecov says 'unknown'.

**To Reproduce**
1. Go to 'https://github.com/kit-data-manager/base-repo'
2. Look codecov badge inside README.md

**Expected behavior**
The current code coverage in % should be displayed on the badge.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14762686/222156966-ef4fcb9e-76e4-4c77-988b-c882a026f142.png)

**Describe the solution you'd like**
Markdown should look like this:
`[![Codecov](https://codecov.io/gh/kit-data-manager/base-repo/graph/badge.svg)](https://codecov.io/gh/kit-data-manager/base-repo)
`
-> [![Codecov](https://codecov.io/gh/kit-data-manager/base-repo/graph/badge.svg)](https://codecov.io/gh/kit-data-manager/base-repo)

**Comment by ThomasJejkal** [comment]
Fixed it at Codecov.
