### ISSUE TITLE
Creator can be deleted when reuse it's ID

### ISSUE THREAD

**Issue by chkalch** [kit-data-manager/base-repo#131]
When creating a new data resource an already existing creator can be removed from an old resource by reusing a creator id again.

**To Reproduce**
1. Create a new data resource, using [this documentation](https://kit-data-manager.github.io/webpage/base-repo/documentation/create-resource.html).
2. Note down the id of the newly created resource and the id the database assigned to the creator.
3. Create another new data resource according to the documentation and set id of the creator to the one from the previous step.
4. request the resource created in step 2

Now the resource doesn't have a creator anymore.

**Expected behavior**
Either creator with same id gets updated and newly created resource gets assigned to it or it isn't allowed to set an id in the request.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser: curl ;)
 - Version: 7.81.0

**Comment by chkalch** [comment]
I can reproduce this behavior for title, whereas it works as expected (update values) on identifier.

**Comment by ThomasJejkal** [comment]
I could reproduce the issue. It only occurs on creation time if a user provides the ID attribute somewhere (except for identifiers, as they are handled differently). This is not intended to be done by the user, as the IDs are primary keys in the database and will be generated automatically by the database. They are only needed for update operations, where they have to be provided to address a certain, existing entity to update.

In the next version of base-repo, user-provided IDs are automatically removed before the resource is written to the database, which will solve this issue.
