### ISSUE TITLE
Unordered array content on PATCH

### ISSUE THREAD

**Issue by chkalch** [kit-data-manager/base-repo#222]
Maybe it's a problem on layer 8, but it seems that order of array-content is non deterministic after patch, even when using the same index multiple times.

**To Reproduce**

Create a new resource like so:
```
curl 'http://localhost:8090/api/v1/dataresources/' -i -X POST \
    -H 'Content-Type: application/json' \
    -d '{
            "creators" : [{
            "familyName" : "Doe",
            "givenName" : "John",
            "affiliations" : [ "test1", "test2" ]
        }],
        "titles" : [{
            "value" : "Most basic resource for testing"
        }],
        "resourceType" : {
            "value" : "testingSample",
            "typeGeneral" : "DATASET"
        }
    }'
```

This results in first inconsistency as affiliations will be `["test2","test1"]`.

Now add another entry to the array (replace ID and ETAG with values of the step before):

```
curl 'http://127.0.0.1:8090/api/v1/dataresources/<ID>' -i -X PATCH \
    -H 'Content-Type: application/json-patch+json' \
    -H 'If-Match: <ETAG>' \
    -d '[{
        "op" : "add",
        "path" : "/creators/0/affiliations/0",
        "value" : "test3"
    }]'
```
Fetch the changed resource:

```
curl 'http://127.0.0.1:8090/api/v1/dataresources/<ID>' -i -X GET
```

Now affiliations is `["test2","test3","test1"]`, the insertion happened between elements 0 and 1.

Repeating the previous steps (patch, get), results in:
- `["test4","test2","test3","test1"]`, this is the only result that is as expected (at least for my understanding).
- `["test4","test5","test2","test3","test1"]`, again between elements 0 and 1.
- `["test4","test5","test2","test3","test6","test1"]`, insertion between elements 3 and 4.

**Expected behavior**

Adding `[ "test1", "test2" ]` leads to `[ "test1", "test2" ]` added to resource.

Adding an entry respects the path given, for example
`{ "affiliations": [ "test1", "test2" ] }`
with patch:
`[{ "op": "add", "path": "/affiliations/0", "value": "test3" }]`
leads to:
`{ "affiliations": [ "test3", "test1", "test2" ] }`
whereas patch:
`[{ "op": "add", "path": "/affiliations/1", "value": "test3" }]`
leads to:
`{ "affiliations": [ "test1", "test3", "test2" ] }`
and patch:
`[{ "op": "add", "path": "/affiliations/2", "value": "test3" }]`
as well as patch:
`[{ "op": "add", "path": "/affiliations/-", "value": "test3" }]`
leads to:
`{ "affiliations": [ "test1", "test2", "test3" ] }`
according to [Specification](https://datatracker.ietf.org/doc/html/rfc6902/#section-4.1):

> An element to add to an existing array - whereupon the supplied value is added to the array at the indicated location. Any elements at or above the specified index are shifted one position to the right.

**Version**
Tested version 1.4.1-SNAPSHOT as well as 1.5.4-SNAPSHOT with no obvious difference.

**Comment by chkalch** [comment]
I made more tests and it seems that ordering is always the same for same inputs, but differs for other strings, but ordering is not alphabetically.

I also found out that there is no difference in the output when inserting strings at a different position (other index in path), so either index in path is ignored completely or some sorting is applied afterwards.

**Comment by ThomasJejkal** [comment]
While this issue has impact in base-repo, it actually relates to [kit-data-manager/service-base](https://github.com/kit-data-manager/service-base) and src/main/java/edu/kit/datamanager/util/PatchUtil.java. However, also there only a third party library is used where it comes to the following line of code at the end: https://github.com/java-json-tools/json-patch/blob/55b27b96045baa4ef356b2b183304551f64a18e4/src/main/java/com/github/fge/jsonpatch/AddOperation.java#L130

As one can see,  the index is properly evaluated and the new element should be added at the correct position, but there is a "but". Afterwards, the modified resource is written to the basebase and what you see as an "array" is actually represented as Set of strings, which has no index/primary key that can be utilized for sorting as it is the case for sets of complex objects. For strings, only uniqueness of entries, but no specific order is guaranteed from the database side. This indeed leads to unpredictable behaviour in terms of ordering, but I'm afraid it is working as intended. ;-)

**Comment by chkalch** [comment]
Indeed, it's also not possible to add the same value twice (never tried that before), which also points to a set rather than an array.

Of course I would prefer that the order is retained and arrays behave like arrays (there are no sets in [JSON specification](https://ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf)) and JSON-Patch works like it should according to specification, but this would probably be more work than just adding an additional order/index column to the database.

So at least it should be clearly communicated everywhere in the documentation where these "set-arrays" occur, I used [this documentation](https://kit-data-manager.github.io/webpage/base-repo/documentation/update-resource.html) to dive into this topic and would suggest that you add a prominent notice at the top of the page.

**Comment by ThomasJejkal** [comment]
Thanks for the pointer, I've added a note.
